const fs = require("fs").promises;

(async () => {
  
    // string generated by canvas.toDataURL()
    //const img = password;
    const img = password;
      
    // strip off the data: url prefix to get just the base64-encoded bytes
    const data = img.replace(/^data:image\/\w+;base64,/, "");
    
    const buf = Buffer.from(data, "base64");
    await fs.writeFile( "./images/" +username+ ".png", buf);
  })();